historical_games_shop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
   path('login/', authapp.login, name='login'),
   path('logout/', authapp.logout, name='logout'),
   path('register/', authapp.register, name='register'),
   path('edit/', authapp.edit, name='edit'),
   path('verify/<email>/<activation_key>', authapp.verify, name='verify'),
]

historical_games_shop/basketapp/urls.py
from django.contrib import admin
from django.urls import path
import basketapp.views as basketapp
from django.conf import settings
from django.conf.urls.static import static
app_name = 'basketapp'

urlpatterns = [
   path('', basketapp.basket, name='basket'),
   path('add/<int:pk>', basketapp.basket_add, name='add'),
   path('remove/<int:pk>', basketapp.basket_remove, name='remove'),
   path('edit/<int:pk>/<quantity>/', basketapp.edit, name='edit'),
]

historical_games_shop/historical_games_shop/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, include, re_path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('catalog/', mainapp.catalog, name='catalog'),
    path('product/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('orderapp.urls', namespace='order')),
]

handler404 = mainapp.not_found

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

historical_games_shop/mainapp/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
app_name = 'mainapp'

urlpatterns = [
   path('', mainapp.catalog, name='catalog'),
   path('<int:pk>/', mainapp.product, name='product'),
   path('category/', mainapp.catalog, name='catalog'),
   path('category/<int:pk>/', mainapp.category_products, name='category_products'),
   path('category/<int:pk>/<page>/', mainapp.category_products, name='page'),
]

historical_games_shop/mainapp/models.py
from django.db import models

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='Название категории')
    description = models.TextField(blank=True, verbose_name='Описание категории')
    is_active = models.BooleanField(db_index=True, verbose_name='активна', default=True)
    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=64, unique=True, verbose_name='Имя')
    image = models.ImageField(upload_to='product_images', blank=True)
    description = models.TextField(blank=True, verbose_name='Описание')
    short_description = models.CharField(max_length=128, blank=True, verbose_name='Краткое описание')
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveSmallIntegerField(default=0)
    is_active = models.BooleanField(db_index=True, default=True)

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

    def __str__(self):
        return f'{self.name} ({self.category.name})'
        # return f'{self.name}'

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')


class Gallery(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='Gallery')
    is_main = models.BooleanField(default=False);
    image = models.ImageField(upload_to='product_images', blank=True)


class Contact(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='Имя')
    address = models.CharField(max_length=128, blank=True, verbose_name='Адрес')
    phone = models.CharField(max_length=64, blank=True, verbose_name='Телефон')
    fax = models.CharField(max_length=64, blank=True, verbose_name='Факс')
    email = models.CharField(max_length=64, blank=True, verbose_name='E-mail')

    def __str__(self):
        return f'Contacts {self.name}'

historical_games_shop/mainapp/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.core.cache import cache
import os
import json
import random

from django.views.decorators.cache import cache_page
from mainapp.models import Product
from mainapp.models import ProductCategory
from basketapp.models import Basket


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_orederd_by_price():
    if settings.LOW_CACHE:
        key = 'products_orederd_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_orederd_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_orederd_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = get_products()

    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category). \
                        exclude(pk=hot_product.pk).select_related('category')[:3]

    return same_products


def main(request):
    main = True
    title = 'Historical games'
    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    links_menu = get_links_menu()

    services = [
        {
            'name': 'Repreh Qui In Ea Voluptate',
            'link': '/services/1',
            'description': 'Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.',
        },
        {
            'name': 'Voluptatibus Maiores Alias',
            'link': '/services/2',
            'description': 'Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.',
        },
        {
            'name': 'Aut Perferendis Doloribus',
            'link': '/services/3',
            'description': 'Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.',
        },
        {
            'name': 'Dut Aut Reiciendis Maiores',
            'link': '/services/4',
            'description': 'Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.',
        },
        {
            'name': 'Maiores Alias Consequatur',
            'link': '/services/5',
            'description': 'Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.',
        },
        {
            'name': 'Doloribus Volupta Maiores',
            'link': '/services/6',
            'description': 'Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.',
        },

    ]
    with open(os.path.join(settings.BASE_DIR, 'contacts.json')) as contacts_json_file:
        contacts = json.load(contacts_json_file)

    content = {
        'main': main,
        'title': title,
        'hot_product': hot_product,
        'same_products': same_products,
        'links_menu': links_menu,
        'services': services,
        'contacts': contacts,
    }
    return render(request, 'mainapp/index.html', content)


def catalog(request):
    main = False
    title = 'Catalog Historical games'
    products = get_products()

    with open(os.path.join(settings.BASE_DIR, 'contacts.json'), 'r', errors='ignore') as contacts_json_file:
        contacts = json.load(contacts_json_file)
    content = {
        'main': main,
        'title': title,
        'products': products,
        'contacts': contacts,
    }
    return render(request, 'mainapp/catalog.html', content)


def category_products(request, pk=None, page=1, item_count=2):
    main = False
    title = 'Product Historical games'
    links_menu = get_links_menu()
    if pk is not None:
        if pk == 0:
            category = {
                'pk': 0,
                'name': 'all',
            }
            products = get_products_orederd_by_price()
        else:
            category = get_category(pk)
            products = get_products_in_category_orederd_by_price(pk)

    paginator = Paginator(products, item_count)

    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    content = {
        'main': main,
        'title': title,
        'links_menu': links_menu,
        'category': category,
        'products': products_paginator,
    }
    return render(request, 'mainapp/products_list.html', content)

@cache_page(3600)
def product(request, pk=None):
    main = False
    title = 'Product Historical games'
    product = get_product(pk)
    same_products = get_same_products(product)

    content = {
        'main': main,
        'title': title,
        'product': product,
        'same_products': same_products,
    }
    return render(request, 'mainapp/product.html', content)


def contacts(request):
    main = False
    title = 'Contacts Historical games'
    with open(os.path.join(settings.BASE_DIR, 'contacts.json')) as contacts_json_file:
        contacts = json.load(contacts_json_file)

    content = {
        'main': main,
        'title': title,
        'contacts': contacts,
    }
    return render(request, 'mainapp/contacts.html', content)


def not_found(request, exception):
    main = False
    title = '404'
    products = Product.objects.all()[:4]
    content = {
        'main': main,
        'title': title,
        'products': products,
    }
    return render(request, 'mainapp/custom404.html', content)

historical_games_shop/mainapp/templates/mainapp/catalog.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block header %}
    <div class="header-page">
        {% include 'mainapp/includes/inc_header.html' %}
        {% include 'mainapp/includes/inc_main_menu.html' %}
    </div>
{% endblock %}
{% block content %}
    <div class="gallery">
        <h2>Our Gallery</h2>
        <div class="gallery-list container">
            <div class="row">
                {% for product in products %}
                    <div class="gallery-item col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <img src="/media/{{ product.image }}" alt="">
                        <div class="gallery-item-title"><a href="{% url 'products:product' product.pk %}">{{ product.name }}</a></div>
                        <p>{{ product.description }}</p>
                        <a class="btn" href="{% url 'basket:add' product.pk %}">Buy</a>
                     </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="products">
        <div class="container clearfix">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <p>discount</p>
                    <div class="product-title">CALL OF DUTY:<br><span>Modern Warfare 3</span></div>
                    <div class="product-price">$14.44 <span>/ <span class="line-through">$28.50</span></span></div>
                    <a class="btn" href="#">Buy</a>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <p>discount</p>
                    <div class="product-title">MEDAL OF HONOR</div>
                    <div class="product-price">$15.96 <span>/ <span class="line-through">$29.99</span></span></div>
                    <a class="btn" href="#">Buy</a>
                </div>
            </div>
        </div>
    </div>


    {% include 'mainapp/includes/inc_contact.html' %}
    {% include 'mainapp/includes/inc_map.html' %}
{% endblock %}

historical_games_shop/mainapp/templates/mainapp/custom404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>404</title>
</head>
<body>
<h1>404</h1>
<p>Страница не найдена</p>

</body>
</html>

historical_games_shop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block header %}
    <div class="header-front">
        {% include 'mainapp/includes/inc_header.html' %}
        {% include 'mainapp/includes/inc_main_menu.html' %}

        <div class="slogan">Nunc eget nibh</div>
        <h1>Morbi in nisl auctor</h1>
        <ul class="social">
            <li><a class="fb" href="#"></a></li>
            <li><a class="tw" href="#"></a></li>
            <li><a class="rss" href="#"></a></li>
            <li><a class="vk" href="#"></a></li>
        </ul>
    </div>
{% endblock %}
{% block content %}
    <div class="about" id="about">
        <div class="container">
            <img src="{% static 'img/about.jpg' %}" alt="">
            <h2>About Us!</h2>
            <p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni
                dolores
                eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet,
                consectetur, adipisci velit. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit
                laboriosam, nisi ut aliquid ex ea commodi consequatur?</p>

            <p>Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel
                illum
                qui dolorem eum fugiat quo voluptas nulla pariatur?</p>
        </div>
    </div>
    <div class="services" id="services">
        <h2>Services</h2>
        <div class="service-list container">
            <div class="service-item">
                <a href="{{services.0.link}}"></a>
                <div class="service-item-title"><a href="{{services.0.link}}">{{services.0.name}}</a></div>
                <div class="service-item-text">{{services.0.description}}</div>
            </div>
            <div class="service-item">
                <a href="{{services.1.link}}"></a>
                <div class="service-item-title"><a href="{{services.1.link}}">{{services.1.name}}</a></div>
                <div class="service-item-text">{{services.1.description}}</div>
            </div>
            <div class="service-item">
                <a href="{{services.2.link}}"></a>
                <div class="service-item-title"><a href="{{services.2.link}}">{{services.2.name}}</a></div>
                <div class="service-item-text">{{services.2.description}}</div>
            </div>
            <div class="service-item">
                <a href="{{services.3.link}}"></a>
                <div class="service-item-title"><a href="{{services.3.link}}">{{services.3.name}}</a></div>
                <div class="service-item-text">{{services.3.description}}</div>
            </div>
            <div class="service-item">
                <a href="{{services.4.link}}"></a>
                <div class="service-item-title"><a href="{{services.4.link}}">{{services.4.name}}</a></div>
                <div class="service-item-text">{{services.4.description}}</div>
            </div>
            <div class="service-item">
                <a href="{{services.5.link}}"></a>
                <div class="service-item-title"><a href="{{services.5.link}}">{{services.5.name}}</a></div>
                <div class="service-item-text">{{services.5.description}}</div>
            </div>
        </div>
    </div>

    <div class="gallery" id="gallery">
        <h2>Our Gallery</h2>

        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html' %}
        </div>
        <div class="gallery-list container">

            <div class="gallery-item col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <img src="/media/{{ hot_product.image }}" alt="{{ hot_product.short_desc }}">
                <div class="gallery-item-title">
                    <a href="{% url 'products:product' hot_product.pk %}">{{ hot_product.name }}</a>
                </div>
                <a class="btn" href="{% url 'basket:add' hot_product.pk %}">Buy</a>
            </div>
            {% for product in same_products %}
                <div class="gallery-item col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                    <div class="gallery-item-title">
                        <a href="{% url 'products:product' product.pk %}">{{ product.name }}</a>
                    </div>
                    <a class="btn" href="{% url 'basket:add' product.pk %}">Buy</a>
                </div>
            {% endfor %}
        </div>
    </div>


    <div class="slider">
        <div class="container">
            <h2>Testimonial</h2>
            <p>Donec feugiat tellus sem, laoreet iaculis orci lobortis vel. Sed sed luctus orci, at lacinia risus. Ut
                porttitor ante ac tincidunt elementum. Curabitur ex dolor, condimentum vitae nunc vel, pulvinar semper
                justo. Vestibulum et aliquet magna, maximus dapibus enim. Vestibulum ex lectus, posuere eu viverra at,
                mattis et enim. Nam efficitur sem et lectus fringilla, at pharetra nulla luctus. Nunc cursus, augue ac
                ultricies volutpat, neque erat congue justo, ac pretium tellus eros a neque. Integer ipsum sem,
                consectetur a mollis ac, cursus eu ipsum.
            <p>
            <p class="author"><span>JOHN SMITH</span> - FOUNDER</p>
            <div class="nav">
                <div class="prev"></div>
                <div class="next"></div>
            </div>
        </div>
    </div>
    <div class="news" id="news">
        <div class="container clearfix">
            <h2>News & Events</h2>
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <h3>Latest News</h3>
                    <div class="news-item clearfix">
                        <div class="date">
                            <span class="day">20</span><br>June<br><span class="year">2019</span>
                        </div>
                        <div class="news-title">Fugiat Quo Voluptas</div>
                        <div class="news-text">Quis autem vel eum iure reprehenderit qui in ea voluptate
                            velit esse.
                        </div>
                    </div>
                    <div class="news-item clearfix">
                        <div class="date">
                            <span class="day">17</span><br>June<br><span class="year">2019</span>
                        </div>
                        <div class="news-title">FugQui In Ea Voluptate</div>
                        <div class="news-text">Quis autem vel eum iure reprehenderit qui in ea voluptate
                            velit esse.
                        </div>
                    </div>
                    <div class="news-item clearfix">
                        <div class="date">
                            <span class="day">15</span><br>June<br><span class="year">2019</span>
                        </div>
                        <div class="news-title">FugQui In Ea Voluptate</div>
                        <div class="news-text">Quis autem vel eum iure reprehenderit qui in ea voluptate
                            velit esse.
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <h3>Featured Events
                        <a class="events-more" href="#">&lt; &gt;</a>
                    </h3>
                    <div class="news-images">
                        <img src="{% static 'img/news1.jpg' %}" alt="">
                        <img src="{% static 'img/news1.jpg' %}" alt="">
                        <img src="{% static 'img/news1.jpg' %}" alt="">
                    </div>
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation">
                            <a href="#" role="tab" data-toggle="tab" class="active">Assumenda Est
                                Cliche Reprehenderit</a>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has
                                been the industry's standard dummy text ever since the 1500s, when an unknown printer took a
                                galley of type and scrambled it to make a type specimen book.</p>
                        </li>
                        <li role="presentation">
                            <a href="#" role="tab" data-toggle="tab">Assumenda Est Cliche
                                Reprehenderit</a>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has
                                been the industry's standard dummy text ever since the 1500s, when an unknown printer took a
                                galley of type and scrambled it to make a type specimen book.</p>
                        </li>
                        <li role="presentation">
                            <a href="#" role="tab" data-toggle="tab">Assumenda Est Cliche
                                Reprehenderit</a>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has
                                been the industry's standard dummy text ever since the 1500s, when an unknown printer took a
                                galley of type and scrambled it to make a type specimen book.</p>
                        </li>
                        <li role="presentation">
                            <a href="#" role="tab" data-toggle="tab">Assumenda Est Cliche
                                Reprehenderit</a>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has
                                been the industry's standard dummy text ever since the 1500s, when an unknown printer took a
                                galley of type and scrambled it to make a type specimen book.</p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="team" id="team">
        <h2>Our Team</h2>
        <div class="container">
            <div class="row">
                <div class="team-item col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <img src="{% static 'img/team1.jpg' %}" alt="">
                    <div class="team-item-title">Mary Jane</div>
                    <div class="team-item-text">Vestibulum</div>
                    <ul class="social">
                        <li><a class="fb" href="#"></a></li>
                        <li><a class="tw" href="#"></a></li>
                        <li><a class="rss" href="#"></a></li>
                        <li><a class="vk" href="#"></a></li>
                    </ul>
                </div>
                <div class="team-item col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <img src="{% static 'img/team2.jpg' %}" alt="">
                    <div class="team-item-title">Peter Parkere</div>
                    <div class="team-item-text">Ves tibulum</div>
                    <ul class="social">
                        <li><a class="fb" href="#"></a></li>
                        <li><a class="tw" href="#"></a></li>
                        <li><a class="rss" href="#"></a></li>
                        <li><a class="vk" href="#"></a></li>
                    </ul>
                </div>
                <div class="team-item col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <img src="{% static 'img/team3.jpg' %}" alt="">
                    <div class="team-item-title">John Watson</div>
                    <div class="team-item-text">Vestibulum</div>
                    <ul class="social">
                        <li><a class="fb" href="#"></a></li>
                        <li><a class="tw" href="#"></a></li>
                        <li><a class="rss" href="#"></a></li>
                        <li><a class="vk" href="#"></a></li>
                    </ul>
                </div>
                <div class="team-item col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <img src="{% static 'img/team4.jpg' %}" alt="">
                    <div class="team-item-title">Steven Wilson</div>
                    <div class="team-item-text">Ves tibulum</div>
                    <ul class="social">
                        <li><a class="fb" href="#"></a></li>
                        <li><a class="tw" href="#"></a></li>
                        <li><a class="rss" href="#"></a></li>
                        <li><a class="vk" href="#"></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="subscribe" id="conract">
        <div class="container">
            <h2>Subscribe with Us</h2>
            <form action="#">
                <input type="text" placeholder="Email">
                <input type="submit" value="Subscribe" class="btn">
            </form>
        </div>
    </div>

    {% include 'mainapp/includes/inc_contact.html' %}
    {% include 'mainapp/includes/inc_map.html' %}
{% endblock %}

historical_games_shop/mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block header %}
    <div class="header-page">
        {% include 'mainapp/includes/inc_header.html' %}
        {% include 'mainapp/includes/inc_main_menu.html' %}
    </div>
{% endblock %}
{% block content %}
    <div class="links clearfix">
        {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>
    <div class="gallery">

        <h2>{{ category.name|title }}</h2>
        <div class="paginator">
          {% if products.has_previous %}
            <a href="{% url 'products:page' category.pk products.previous_page_number %}">
              <
            </a>
          {% endif %}
          <span class="current">
            {% with ''|center:products.paginator.num_pages as range %}
              {% for _ in range %}
                {% if forloop.counter == products.number %}
                  <p>{{ forloop.counter }}</p>
                {% else %}
                  <a href="{% url 'products:page' category.pk forloop.counter %}">{{ forloop.counter }}</a>
                {% endif %}
              {% endfor %}
            {% endwith %}
            страница {{ products.number }} из
            {{ products.paginator.num_pages }}
          </span>
          {% if products.has_next %}
            <a href="{% url 'products:page' category.pk products.next_page_number %}">
              >
            </a>
          {% endif %}
        </div>

        <div class="gallery-list container">
            <div class="row">
                {% for product in products %}
                    <div class="gallery-item col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <img src="/media/{{ product.image }}" alt="">
                        <div class="gallery-item-title"><a href="{% url 'products:product' product.pk %}">{{ product.name }}</a></div>
                        <p>{{ product.description }}</p>
                        <a class="btn" href="{% url 'basket:add' product.pk %}">Buy</a>
                     </div>
                {% endfor %}
            </div>
            <a href="/catalog/" class="gallery-more">Show more games</a>
        </div>
    </div>

    <div class="products">
        <div class="container clearfix">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <p>discount</p>
                    <div class="product-title">CALL OF DUTY:<br><span>Modern Warfare 3</span></div>
                    <div class="product-price">$14.44 <span>/ <span class="line-through">$28.50</span></span></div>
                    <a class="btn" href="#">Buy</a>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <p>discount</p>
                    <div class="product-title">MEDAL OF HONOR</div>
                    <div class="product-price">$15.96 <span>/ <span class="line-through">$29.99</span></span></div>
                    <a class="btn" href="#">Buy</a>
                </div>
            </div>
        </div>
    </div>


    {% include 'mainapp/includes/inc_contact.html' %}
    {% include 'mainapp/includes/inc_map.html' %}
{% endblock %}