historical_games_shop/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
   path('users/read/', adminapp.UsersListView.as_view(), name='users'),
   path('users/read/<page>/', adminapp.UsersListView.as_view(), name='page'),
   # path('users/read/', adminapp.users, name='users'),
   path('users/create/', adminapp.user_create, name='user_create'),
   path('users/update/<pk>/', adminapp.user_update, name='user_update'),
   path('users/delete/<pk>/', adminapp.user_delete, name='user_delete'),

   path('categories/create/', adminapp.category_create, name='category_create'),
   # path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
   path('categories/read/', adminapp.categories, name='categories'),
   # path('categories/update/<pk>/', adminapp.category_update, name='category_update'),
   path('categories/update/<pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
   path('categories/delete/<pk>/', adminapp.category_delete, name='category_delete'),

   path('products/create/category/<pk>/', adminapp.product_create, name='product_create'),
   path('products/read/category/<pk>/', adminapp.products, name='products'),
   path('products/read/<pk>/', adminapp.product, name='product'),
   path('products/update/<pk>/', adminapp.product_update, name='product_update'),
   path('products/delete/<pk>/', adminapp.product_delete, name='product_delete'),

   path('orders_list/read/', adminapp.OrdersListView.as_view(), name='orders'),
   path('order/<pk>/status/', adminapp.order_status_change, name='order_status_change'),
]

historical_games_shop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
   path('login/', authapp.login, name='login'),
   path('logout/', authapp.logout, name='logout'),
   path('register/', authapp.register, name='register'),
   path('edit/', authapp.edit, name='edit'),
   path('verify/<email>/<activation_key>', authapp.verify, name='verify'),
]

historical_games_shop/basketapp/urls.py
from django.contrib import admin
from django.urls import path
import basketapp.views as basketapp
from django.conf import settings
from django.conf.urls.static import static
app_name = 'basketapp'

urlpatterns = [
   path('', basketapp.basket, name='basket'),
   path('add/<int:pk>', basketapp.basket_add, name='add'),
   path('remove/<int:pk>', basketapp.basket_remove, name='remove'),
   path('edit/<int:pk>/<quantity>/', basketapp.edit, name='edit'),
]

historical_games_shop/historical_games_shop/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, include, re_path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('catalog/', mainapp.catalog, name='catalog'),
    path('product/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('orderapp.urls', namespace='order')),
]

handler404 = mainapp.not_found

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

historical_games_shop/mainapp/urls.py
from django.contrib import admin
from django.urls import path
import mainapp.views as mainapp
from django.conf import settings
from django.conf.urls.static import static
app_name = 'mainapp'

urlpatterns = [
   path('', mainapp.catalog, name='catalog'),
   path('<int:pk>/', mainapp.product, name='product'),
   path('category/', mainapp.catalog, name='catalog'),
   path('category/<int:pk>/', mainapp.category_products, name='category_products'),
   path('category/<int:pk>/<page>/', mainapp.category_products, name='page'),
]

historical_games_shop/orderapp/urls.py
from django.contrib import admin
from django.urls import path
import orderapp.views as orderapp
from django.conf import settings
from django.conf.urls.static import static


app_name = 'orderapp'

urlpatterns = [
    path('', orderapp.OrderList.as_view(), name='order_list'),
    path('create/', orderapp.OrderItemsCreate.as_view(), name='order_create'),
    path('read/<pk>/', orderapp.OrderRead.as_view(), name='order_read'),
    path('update/<pk>/', orderapp.OrderItemsUpdate.as_view(), name='order_update'),
    path('delete/<pk>/', orderapp.OrderDelete.as_view(), name='order_delete'),
    path('forming/<pk>/', orderapp.order_forming_complete, name='order_forming_complete'),
    path('product_price_update/<pk>/', orderapp.product_price_update, name='product_price_update'),

]

historical_games_shop/mainapp/models.py
from django.db import models

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='Название категории')
    description = models.TextField(blank=True, verbose_name='Описание категории')
    is_active = models.BooleanField(db_index=True, verbose_name='активна', default=True)
    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=64, unique=True, verbose_name='Имя')
    image = models.ImageField(upload_to='product_images', blank=True)
    description = models.TextField(blank=True, verbose_name='Описание')
    short_description = models.CharField(max_length=128, blank=True, verbose_name='Краткое описание')
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveSmallIntegerField(default=0)
    is_active = models.BooleanField(db_index=True, default=True)

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

    def __str__(self):
        return f'{self.name} ({self.category.name})'
        # return f'{self.name}'

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')


class Gallery(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='Gallery')
    is_main = models.BooleanField(default=False);
    image = models.ImageField(upload_to='product_images', blank=True)


class Contact(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='Имя')
    address = models.CharField(max_length=128, blank=True, verbose_name='Адрес')
    phone = models.CharField(max_length=64, blank=True, verbose_name='Телефон')
    fax = models.CharField(max_length=64, blank=True, verbose_name='Факс')
    email = models.CharField(max_length=64, blank=True, verbose_name='E-mail')

    def __str__(self):
        return f'Contacts {self.name}'

historical_games_shop/mainapp/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.core.cache import cache
import os
import json
import random

from django.views.decorators.cache import cache_page
from mainapp.models import Product
from mainapp.models import ProductCategory
from basketapp.models import Basket


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_orederd_by_price():
    if settings.LOW_CACHE:
        key = 'products_orederd_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_orederd_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_orederd_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = get_products()

    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category). \
                        exclude(pk=hot_product.pk).select_related('category')[:3]

    return same_products


def main(request):
    main = True
    title = 'Historical games'
    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    links_menu = get_links_menu()

    services = [
        {
            'name': 'Repreh Qui In Ea Voluptate',
            'link': '/services/1',
            'description': 'Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.',
        },
        {
            'name': 'Voluptatibus Maiores Alias',
            'link': '/services/2',
            'description': 'Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.',
        },
        {
            'name': 'Aut Perferendis Doloribus',
            'link': '/services/3',
            'description': 'Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.',
        },
        {
            'name': 'Dut Aut Reiciendis Maiores',
            'link': '/services/4',
            'description': 'Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.',
        },
        {
            'name': 'Maiores Alias Consequatur',
            'link': '/services/5',
            'description': 'Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.',
        },
        {
            'name': 'Doloribus Volupta Maiores',
            'link': '/services/6',
            'description': 'Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.',
        },

    ]
    with open(os.path.join(settings.BASE_DIR, 'contacts.json')) as contacts_json_file:
        contacts = json.load(contacts_json_file)

    content = {
        'main': main,
        'title': title,
        'hot_product': hot_product,
        'same_products': same_products,
        'links_menu': links_menu,
        'services': services,
        'contacts': contacts,
    }
    return render(request, 'mainapp/index.html', content)


def catalog(request):
    main = False
    title = 'Catalog Historical games'
    products = get_products()

    with open(os.path.join(settings.BASE_DIR, 'contacts.json'), 'r', errors='ignore') as contacts_json_file:
        contacts = json.load(contacts_json_file)
    content = {
        'main': main,
        'title': title,
        'products': products,
        'contacts': contacts,
    }
    return render(request, 'mainapp/catalog.html', content)


def category_products(request, pk=None, page=1, item_count=2):
    main = False
    title = 'Product Historical games'
    links_menu = get_links_menu()
    if pk is not None:
        if pk == 0:
            category = {
                'pk': 0,
                'name': 'all',
            }
            products = get_products_orederd_by_price()
        else:
            category = get_category(pk)
            products = get_products_in_category_orederd_by_price(pk)

    paginator = Paginator(products, item_count)

    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    content = {
        'main': main,
        'title': title,
        'links_menu': links_menu,
        'category': category,
        'products': products_paginator,
    }
    return render(request, 'mainapp/products_list.html', content)

@cache_page(3600)
def product(request, pk=None):
    main = False
    title = 'Product Historical games'
    product = get_product(pk)
    same_products = get_same_products(product)

    content = {
        'main': main,
        'title': title,
        'product': product,
        'same_products': same_products,
    }
    return render(request, 'mainapp/product.html', content)


def contacts(request):
    main = False
    title = 'Contacts Historical games'
    with open(os.path.join(settings.BASE_DIR, 'contacts.json')) as contacts_json_file:
        contacts = json.load(contacts_json_file)

    content = {
        'main': main,
        'title': title,
        'contacts': contacts,
    }
    return render(request, 'mainapp/contacts.html', content)


def not_found(request, exception):
    main = False
    title = '404'
    products = Product.objects.all()[:4]
    content = {
        'main': main,
        'title': title,
        'products': products,
    }
    return render(request, 'mainapp/custom404.html', content)

historical_games_shop/mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
  <li>
    <a href="{% url 'products:category_products' 0 %}"
       class="{% if request.resolver_match.kwargs.pk == '0' %}
                active
              {% endif %}">
      All
    </a>
  </li>
  {% for link in links_menu %}
    <li>
      <a href="{% url 'products:category_products' link.pk %}"
         class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}
                  active
                {% endif %}">
        {{ link.name }}
      </a>
    </li>
  {% endfor %}
</ul>

historical_games_shop/mainapp/templates/mainapp/includes/inc_contact.html
<div class="contact">
    <div class="container clearfix">
        <h2>Contact Us</h2>
        <div class="w50">
            <h3>Get in touch with us</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sheets
                containing Lorem Ipsum passages sed do, At vero eos et accusamus et
                iusto odio digs qui blanditiis</p>
            <p>{{contacts.address}}<br>{{contacts.address_line2}}</p>
            <p>Telephone : {{contacts.phone}}</p>
            <p>FAX : {{contacts.fax}}</p>
            <p>Email : <a href="mailto:{{contacts.email}}">{{contacts.email}}</a></p>
        </div>
        <div class="w50">
            <form action="#">
                <input type="text" placeholder="Name"><br>
                <input class="email" type="text" placeholder="Email"><br>
                <textarea placeholder="Message"></textarea><br>
                <input class="btn" type="submit" value="Submit">
            </form>
        </div>
    </div>
</div>

historical_games_shop/mainapp/templates/mainapp/includes/inc_header.html
<div class="header">
    <div class="header-back"></div>
    <div class="container">
        <a href="{% url 'main' %}" class="logo">Historical<br><span>Games</span></a>
        <a href="tel:+1234567890" class="phone">+123 456 7890</a>
        <a href="mailto:info@example.com" class="email">info@example.com</a>
        <div class="search">
            <form action="#">
                <input type="text" placeholder="Search">
                <input type="submit">
            </form>
        </div>
        <div class="user-menu">
            {% if user.is_authenticated %}
                <div class="dropdown">
                    <a class="dropdown-toggle lk" href="" data-toggle="dropdown">
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{% url 'auth:edit' %}">
                                профиль
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'order:order_list' %}">
                                заказы
                            </a>
                        </li>
                    </ul>
                </div>

                <a href="{% url 'basket:basket' %}" class="basket{% if request.resolver_match.url_name == 'main' %} active{% endif %}">
                    {% if basket %}
                        {{ basket.0.total_quantity }}
                        ${{ basket.0.total_cost | floatformat:0 }}
                    {% endif %}
                </a>
                {% if user.is_superuser %}
                    <a class="admin" href="{% url 'admin:users' %}"></a>
                {% endif %}
                <a class="logout" href="{% url 'auth:logout' %}"></a>
            {% else %}
                 <a href="{% url 'auth:login' %}">войти</a>
            {% endif %}
        </div>
    </div>
</div>

historical_games_shop/mainapp/templates/mainapp/includes/inc_main_menu.html
    <ul class="menu">
        <li><a href="{% url 'main' %}" {% if request.resolver_match.url_name == 'main' %}class="active"{% endif %} >Home</a></li>
        <li><a href="{% url 'main' %}#about">About</a></li>
        <li><a href="{% url 'main' %}#services">Services</a></li>
        <li><a href="{% url 'main' %}#gallery">Gallery</a></li>
        <li><a href="{% url 'main' %}#news">News</a></li>
        <li><a href="{% url 'main' %}#team">Team</a></li>
        <li><a href="{% url 'contacts' %}" {% if request.resolver_match.url_name == 'contacts' %}class="active"{% endif %} >Contact Us</a></li>
    </ul>

historical_games_shop/mainapp/templates/mainapp/includes/inc_map.html
<div class="map">
    <div class="container clearfix">
        <h2>Route Map</h2>
        <script async
                src="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=929LFVnJCgep9n0vtxFEkYl8KkxiR49q&amp;width=100%25&amp;height=298&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"></script>
    </div>
</div>